version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: csarda-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: csarda-web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mariadb
        container_name: csarda-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: csarda
            MYSQL_USER: csarda_user
            MYSQL_PASSWORD: csarda_pass
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
